# Generated by Django 4.2.29 on 2026-03-04 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(blank=True, help_text='Unique key derived from email+phone hash or generated.', max_length=255, null=True, unique=True)),
                ('original_file_name', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('resume_source', models.CharField(choices=[('upload', 'Upload'), ('email', 'Email')], default='upload', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('extracting', 'Extracting'), ('storing', 'Storing'), ('standardizing', 'Standardizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('dataverse_record_id', models.CharField(blank=True, max_length=255)),
                ('standardized_file_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume Record',
                'verbose_name_plural': 'Resume Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('step', models.CharField(help_text='Processing step name', max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.resumerecord')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_missing', models.BooleanField(default=False)),
                ('resume_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_fields', to='api.resumerecord')),
            ],
            options={
                'unique_together': {('resume_record', 'field_name')},
            },
        ),
    ]
